### ISSUE TITLE
Application startup exception (missing '{' or '}')

### ISSUE THREAD

**Issue by Dany-R** [gnschenker/dotnetpro-registration-app#1]
Wenn ich die webapi starte, bekomme ich eine `Application startup exception`:

> System.ArgumentException: There is an incomplete parameter in the route template. Check that each '{' character has a matching '}' character. (Parameter 'routeTemplate')

Dies liegt an einem Syntax-Fehler im Repo, Datei `ApplicationsController.cs`, Zeile 21, wo die schließende geschweifte Klammer fehlt, was so aussehen müsste:
`[HttpGet("{applicationId}")]`

Als Neuling hat mich das recht viel Zeit gekostet, weil der Fehler auf `Startup.cs` Zeile 47 (`endpoints.MapControllers();`) verwiesen hatte (auf Fehler in Attributen kann halt nicht verwiesen werden).

Cheers, Dany

**Comment by gnschenker** [comment]
Thank you for reporting and sorry for the troubles...
Best
Gabriel

**Comment by gnschenker** [comment]
fixed

**Comment by Dany-R** [comment]
Sorry, it's me again, but now you removed the (normal) closing brace of `HttpGet()` ;)

**Comment by gnschenker** [comment]
uuuppss.. fixed!

**Comment by gnschenker** [comment]
Awesome, thanks! Fixed it now
